'use strict'
const types = {
	//首页电影数据
	INDEX_SET_TOP250: 'INDEX_SET_TOP250',
	INDEX_SET_WILLSHOW: 'INDEX_SET_WILLSHOW',
	INDEX_SET_ISSHOW: 'INDEX_SET_ISSHOW',
	//搜索页数据
	SEARCH_SET_HOTEMOJI: 'SEARCH_SET_HOTEMOJI',
	SEARCH_SET_SEARCHRESULT: 'SEARCH_SET_SEARCHRESULT',
	SEARCH_CHANGE_LOADING: 'SEARCH_CHANGE_LOADING',

}
export default types